# Generated by Django 4.2.6 on 2023-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('createdTime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
