# Generated by Django 4.2.6 on 2023-11-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_contact_delete_student_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='createdTime',
            new_name='time',
        ),
    ]
